require("./modelCreate").default.register("modelCreate");
require("./modelCount").default.register("modelCount");
require("./modelQuery").default.register("modelQuery");
require("./config").default.register("config");
require("./configSync").default.register("configSync");
require("./loginUser").default.register("loginUser");
require("./currentAccount").default.register("currentAccount");
require("./currentUser").default.register("currentUser");
require("./init").default.register("init");
